### ISSUE TITLE
멀티플레이중 한명이 단말기를 꺼도 게임이 일정시간 계속되는 이슈

### ISSUE THREAD

**Issue by june0313** [Maze-of-memories/origin#4]
[요약]
- 멀티플레이 게임 중 비정상적으로 어플이 종료되는 경우(ex 단말기 종료, 어플 강제 종료 등등..)에도 게임이 일정시간 지속됨

[Steps]
1. 멀티플레이 매치를 시작한다.
2. 한 쪽 단말기의 전원을 끈다.

[Error]
- 전원을 끄지 않은 단말기에서 일정시간 게임이 지속된다.
- 상대방이 턴을 넘겨주지 않아 일정시간동안 말을 움직일 수 없음

**Comment by shfksekdrms2** [comment]
good
